### ISSUE TITLE
PMS and Slave not sharing CPU Processing

### ISSUE THREAD

**Issue by jwmoss** [wnielson/Plex-Remote-Transcoder#1]
See below. The bottom terminal is the slave, the top is the plex media server. It's currently transcoding a movie, yet only the slave is transcoding!

![load_balance](https://cloud.githubusercontent.com/assets/2729151/9674754/f8496114-5282-11e5-9386-aee34e7274a8.gif)

**Comment by wnielson** [comment]
Have you added the master as a transcode host?  By default, the master is not considered unless no slaves are added/available.

**Comment by jwmoss** [comment]
I thought that's what adding it using "sudo prt install_host" and selecting 127.0.0.1 did as a plex user. 
Sent from iPhone

On Thu, Sep 3, 2015 at 6:37 PM -0700, "Weston Nielson" notifications@github.com wrote:

Have you added the master as a transcode host?  By default, the master is not considered unless no slaves are added/available.

**Comment by wnielson** [comment]
Can you paste your configuration file?  Make sure you 'su plex' then copy '~/.prt.conf'.

**Comment by jwmoss** [comment]
Plex Media Server prt.conf settings - 

{
    "servers_script": null, 
    "ipaddress": "172.16.1.228", 
    "path_script": null, 
    "logging": {
        "loggers": {
            "prt": {
                "handlers": [
                    "file_handler"
                ], 
                "propagate": "no", 
                "level": "DEBUG"
            }
        }, 
        "handlers": {
            "file_handler": {
                "backupCount": 20, 
                "level": "INFO", 
                "encoding": "utf8", 
                "filename": "prt.log", 
                "formatter": "simple", 
                "class": "logging.handlers.RotatingFileHandler", 
                "maxBytes": 10485760
            }
        }, 
        "version": 1, 
        "disable_existing_loggers": false, 
        "formatters": {
            "simple": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            }
        }
    }, 
    "servers": {
        "172.16.1.216": {
            "port": "22", 
            "user": "plex"
        }, 
        "127.0.0.1": {
            "port": "22", 
            "user": "plex"
        }
    }
}

Slave prt.conf settings - 

{
    "servers_script": null, 
    "ipaddress": "172.16.1.228", 
    "path_script": null, 
    "logging": {
        "loggers": {
            "prt": {
                "handlers": [
                    "file_handler"
                ], 
                "propagate": "no", 
                "level": "DEBUG"
            }
        }, 
        "handlers": {
            "file_handler": {
                "backupCount": 20, 
                "level": "INFO", 
                "encoding": "utf8", 
                "filename": "prt.log", 
                "formatter": "simple", 
                "class": "logging.handlers.RotatingFileHandler", 
                "maxBytes": 10485760
            }
        }, 
        "version": 1, 
        "disable_existing_loggers": false, 
        "formatters": {
            "simple": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            }
        }
    }, 
    "servers": {
        "172.16.1.216": {
            "port": "22", 
            "user": "plex"
        }, 
        "127.0.0.1": {
            "port": "22", 
            "user": "plex"
        }
    }
}

**Comment by wnielson** [comment]
Oh, I see--you are only transcoding one item.  A single transcode job will only run on a **single host**.  If you start a second transcode job, you should see it run on the master.

**Comment by jwmoss** [comment]
Ah so there is currently no way to split the transcode job on both the master and the slave with with one item?

**Comment by jwmoss** [comment]
Looks like the slave is the only PC doing the transcoding, even with 2 items playing at once, and not the master transcoding the 2nd stream. 
![screen_shot_2015-09-03_at_11_17_27_pm](https://cloud.githubusercontent.com/assets/2729151/9675960/7af2243e-5292-11e5-9fcc-40936050b92d.jpg)

**Comment by wnielson** [comment]
Yeah, you're right.  OK, try this.  `su plex` and then `ssh plex@127.0.0.1`.  Can you login OK?  If that still doesn't work, edit your config and change the `file_handler` `filename` option to `/tmp/prt.log`.  Try starting the transcodes again and then take a look at the log file.  You can also send me the log and I'll take a look.

**Comment by jwmoss** [comment]
I can login fine on the PMS using su plex and ssh into localhost. Would you like me to send the logs after setting file_handler to /tmp/prt.log and rebooting both master and slave?

**Comment by wnielson** [comment]
Hopefully the logs will help us here.  Just update the conf file on the master (the slave conf files aren't used).  You don't need to reboot, just restart the transcoding jobs.  Just change the "filename" setting to `/tmp/prt.log`, fire up some transcode jobs then send the log file.

**Comment by jwmoss** [comment]
http://pastebin.com/raw.php?i=Chwffbc2

Looks like it worked. Had to reboot the master and the slave. Does this currently support load-balancing 1 stream or is that in development?

**Comment by wnielson** [comment]
Looks like it is working, yes.  Not sure why a reboot was required though.

Load-balancing one stream is (currently) beyond the scope of this project as it would require modification of the Plex transcoder which is closed-source, unfortunately.

**Comment by DrEVILish** [comment]
FYI I have been doing research into this the Plex Transcoder is available upon request because it's built upon the ffmpeg meaning it cannot be incorporated into closed source programs.

http://files.plexapp.com/elan/ffmpeg/PlexTranscoder.tar.bz2
http://files.plexapp.com/elan/ffmpeg/PlexNewTranscoder.tar.bz2

https://trac.ffmpeg.org/ticket/2974
