### ISSUE TITLE
PRT - Synology NAS - Install

### ISSUE THREAD

**Issue by DrEVILish** [wnielson/Plex-Remote-Transcoder#2]
I'm using a synology NAS as my base for Plex (well trying to have previously been using a windows HTPC) would like to centralise all my servery stuff. NAS - hosts the files and PMS, then a few small PCs connected to the network run as the transcoders.

I installed Python27 and Python27 setuptools onto the NAS (3.10.35 GNU/Linux)
got all through the GIT and went to do the "sudo prt install" and got ->

"
%> sudo prt install
Traceback (most recent call last):
  File "/bin/prt", line 9, in <module>
    load_entry_point('prt==0.2.0', 'console_scripts', 'prt_remote')()
  File "/usr/local/lib/python2.7/site-packages/prt-0.2.0-py2.7.egg/prt.py", line 246, in transcode_remote
    return transcode_local()
  File "/usr/local/lib/python2.7/site-packages/prt-0.2.0-py2.7.egg/prt.py", line 167, in transcode_local
    proc = subprocess.Popen(args)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
"

Really interested in your project, many thanks.

**Comment by wnielson** [comment]
Is this the full log?  Seems like there is an issue with setuptools.  I need more details to help here...

**Comment by DrEVILish** [comment]
That is the full log afaik, Yeah sorry I'm more of just a tinkerer and haven't used Python much, I'll take another look tonight and see if I can't work out what your script is trying to achieve and write something for Mint.

The copy of Linux running on the Synology nas is a variant of LinuxMint. It has PMS installed at:

a) /volume1/@appstore/Plex Media Server
b) /var/packages/Plex Media Server
c) /volume1/Plex

c) contains the library and tmp_transcoding folder

**Comment by DrEVILish** [comment]
A "cool" option to add would be to add remote checker, if a RTS is not online use original inbuilt transcoder. A simple failover.

Also adding a remote transcode server(RTS) instead of telling the server what ip etc they are at, should be the other way around boot up a RTS and tell it the host IP address that signals to the host that it's on and ready.

If an RTS goes down it doesn't keep hunting for it. If the host can't talk to a RTS it doesn't keep trying it just moves on to the next RTS. When the RTS comes back online it signals again telling the host it's available for the next transcode.

**Comment by wnielson** [comment]
> A "cool" option to add would be to add remote checker, if a RTS is not online use original inbuilt transcoder. A simple failover.

It already works this way.

> Also adding a remote transcode server(RTS) instead of telling the server what ip etc they are at, should be the other way around boot up a RTS and tell it the host IP address that signals to the host that it's on and ready.

Yeah, this is another option.

> If an RTS goes down it doesn't keep hunting for it. If the host can't talk to a RTS it doesn't keep trying it just moves on to the next RTS. When the RTS comes back online it signals again telling the host it's available for the next transcode.

This is how it works now.  If a host isn't available, it is ignored and the next host is tried.  The next time a transcode is requested, it is checked again and if available it is used.

**Comment by DrEVILish** [comment]
I have some good news I'm 99.9% sure it's not a fault with your code :D 

Tried a VM version of the NAS I'm using worked perfectly - scarily well in fact :D

**Comment by wnielson** [comment]
> I have some good news I'm 99.9% sure it's not a fault with your code :D

That's what I suspected, but without further debug info I can't help figure out why setuptools is failing.

**Comment by DrEVILish** [comment]
One issue I have had on this version is after - sudo python setup.py install 
I have to 
"sudo chmod +r /usr/lib/python2.7/site-packages/prt-0.2.0-py2.7.egg"

because otherwise it only has 
"-rwx--x--x" permissions and it for some reason the plex user wouldn't run "prt add_host" kept giving me another setuptools error.

Thought I cracked it the other night hit a different snag. also due to the fact my NAS has plex installed in totally different places so I have created some symlinks to the places.

ln -s /volume1/@appstore/Plex\ Media\ Server/ /usr/lib/plexmediaserver
ln -s /volume1/Plex/ /var/lib/plexmediaserver

also the original naming scheme didn't help as they had spaces in which causes major pains when trying to nfs to those folders so I symlinked instead of editing every reference to the original paths...

**Comment by DrEVILish** [comment]
I'm a little lost now, I've been trying to get this worked, I set it up as you said with two Ubuntu machines and worked great while trying on a different flavor of Linux I've had nothing but issues. 90% due to my ineptitude of not actively using Linux in a long while.

I have tailed the log and get when hitting play on a video. Which looks pretty good to me apart from the 'u' all over the place... 

http://192.168.1.190:32400/video/:/transcode/session/vr67jxpnatm4pldi/progress2015-10-13 07:46:41,390 - prt - INFO - Host with minimum load is '192.168.0.1'
2015-10-13 07:46:41,390 - prt - INFO - Using transcode host '192.168.0.1'
2015-10-13 07:46:41,390 - prt - INFO - Launching transcode_remote with args ['ssh', u'plex@192.168.0.1', '-p', u'22', u"export LD_LIBRARY_PATH=/usr/lib/plexmediaserver:$LD_LIBRARY_PATH;cd /volume1/Plex;prt_local -i /volume1/video/Mos/cc.15.05.22.natalie.8749.mp4 -filter_complex '[0:#0x01]scale=w=min(568\,iw):h=min(320\,ih):force_original_aspect_ratio=decrease[0]' -map '[0]' -codec:0 libx264 -crf:0 22 -pix_fmt:0 yuv420p -maxrate:0 355k -bufsize:0 710k -presetveryfast -x264opts:0 cabac=0:8x8dct=1:bframes=0:subme=3:me_range=4:rc_lookahead=10:me=hex -map '0:#0x02' -codec:1 aac -strict:1 experimental -cutoff:1 15000 -channel_layout:1 stereo -b:1 161k -f matroska -avoid_negative_ts disabled p_metadata -1 - -start_at_zero -copyts -y -nostats -loglevel quiet -loglevel_plex error -progressurl http://192.168.1.190:32400/video/:/transcode/session/ezdrevzorusg7gb9/progress"]

Do you have any tips for testing if any of the individual items are working.

When running:

prt_local on the PMS server I got the Plex Transcoder v3.003.15.0714-0315 message, I'm guessing that is supposed to happen, but when running prt_local or prt_remote on the slaves I get a traceback->
ValueError: Unable to configure handler u'file_handler': [Errno 13] Permission denied: u'/var/lib/plexmediaserver/prt.log'

that is typed exactly I'm confused about the 'u's again.

below are the scripts I have been using to run my NAS and slaves. I typed it up as easier to copy and paste, while testing.

# CONFIGURE PMS HOST

Install PMS from package manager

ln -s /volume1/@appstore/Plex\ Media\ Server/ /usr/lib/plexmediaserver
ln -s /volume1/Plex/ /var/lib/plexmediaserver

## sudo nano /etc/passwd

/var/lib/plexmediaserver:bin/sh

git clone https://github.com/wnielson/Plex-Remote-Transcoder.git
cd Plex-Remote-Transcoder
sudo python setup.py install

ls /usr/lib/python2.7/site-packages (check installed)?
sudo chmod +r /usr/lib/python2.7/site-packages/prt-0.2.0-py2.7.egg

sudo prt install

sudo mv /root/.prt.conf /var/lib/plexmediaserver
cd /var/lib/plexmediaserver
sudo chown plex:users .prt.conf
cd /usr/lib/python2.7/site-packages/

sudo su plex
prt add_host

sudo nano /etc/exports
->
/var/lib/plexmediaserver 192.168.0.0/24(ro,sync,no_subtree_check)
/usr/lib/plexmediaserver 192.168.0.0/24(ro,sync,no_subtree_check)
/opt/plex/tmp 192.168.0.0/24(rw,sync,no_subtree_check)
/volume1/video 192.168.0.0/24(ro,sync,no_subtree_check)

/usr/syno/etc/rc.d/S83nfsd.sh restart

# CONFIGURE SLAVE

git clone https://github.com/wnielson/Plex-Remote-Transcoder.git
cd Plex-Remote-Transcoder
sudo python setup.py install

+MASTER - id plex

sudo useradd --uid 1026 --gid 100 plex --home /var/lib/plexmediaserver --no-create-home

sudo nano /etc/fstab
->
192.168.1.190:/var/lib/plexmediaserver /var/lib/plexmediaserver nfs defaults 0 0
192.168.1.190:/usr/lib/plexmediaserver /usr/lib/plexmediaserver nfs defaults 0 0
192.168.1.190:/opt/plex/tmp /opt/plex/tmp nfs defaults 0 0
192.168.1.190:/volume1/video /volume1/video nfs defaults 0 0

sudo mkdir -p /var/lib/plexmediaserver
sudo mkdir -p /usr/lib/plexmediaserver
sudo mkdir -p /opt/plex/tmp
sudo mkdir -p /volume1/video

sudo mount -a

# Last MASTER CONFIG

sudo su plex
ssh-keygen
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

I use http://xpenology.me/downloads/ to create my SynologyVM for testing.
Any help would be greatly appreciated let me know if there is anything I can test to be of more use.
