### ISSUE TITLE
remove_host issue

### ISSUE THREAD

**Issue by shushry** [wnielson/Plex-Remote-Transcoder#24]
First off - this project is an AMAZING piece of work.   Is there a donation bucket?    This has really enabled our plex project at this end.

Working on some automation for creating / destroying slaves on demand, and "remove_host hostname" reports a successful message, but doesn't actually remove the host from prt.conf

Any ideas?

**Comment by DrEVILish** [comment]
I believe the problem is that after it runs remove_host from the config:servers array it doesn't save the config back to a file. I have proposed a fix #25  to this issue to @wnielson

**Comment by shushry** [comment]
I noticed that as well - i'll probably patch locally -
