### ISSUE TITLE
rpi2

### ISSUE THREAD

**Issue by pisteps** [wnielson/Plex-Remote-Transcoder#30]
hi,
is the plex-remote-transcoder supposed to work when the master is an rpi2 (pms 1.0 installed using the netgear ARM 6.x RN2xx)?

trying to follow the guide (PMS-v1 code) but when at the following command:
`sudo install -o plex -g plex ~/.prt.conf ~plex/`

i get:
`install: invalid group ‘plex’`

there is a plex user created when i install pms, but no plex group.
if i try to add a plex group, then the message i get after:
`sudo install -o plex -g plex ~/.prt.conf ~plex/’`

is
`install: cannot stat ‘/home/pi/.prt.conf’: No such file or directory`

**Comment by wnielson** [comment]
It is either because your `plex` user's home directory is set to `/home/pi`, which doesn't exist, or you haven't created `~/.prt.conf` as your normal user (`pi`?).

**Comment by pisteps** [comment]
thank you. i deleted the plex user and created a new plex user. then followed your guide as root user. this time didnt get any error message. looks like went fine.
now i am struggling with the nfs server. not working, the raspberry seems like it is not sharing.
i can try with a samba share (that one i know it works): but i am not sure if your code works indipendently from the way the folders are shared

**Comment by wnielson** [comment]
The method of file sharing doesn't matter--if you want to use CIFS/Samba, feel free.  As long as the correct directories are shared things should still work.

**Comment by pisteps** [comment]
excellent. directories now are shared with a ubuntu virtual box.

last bit of the wall... can't connect to the slave with ssh.
i get 
`Permission denied (publickey,keyboard-interactive)`
but password is correct

**Comment by wnielson** [comment]
By default the `plex` user does not have a password and authentication must be configured to use keys instead.  On the host, change to the `plex` user, generate an ssh key and then add it to the `authorized_keys` file:

```
sudo su plex
ssh-keygen
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
```

**Comment by pisteps** [comment]
thank you.
i don't get it this part

that is what i did on the master
`plex@minibian:~$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/plex/.ssh/id_rsa): 
/home/plex/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/plex/.ssh/id_rsa.
Your public key has been saved in /home/plex/.ssh/id_rsa.pub.
The key fingerprint is:
02:89:4e:e9:b0:a1:ae:cb:a1:e9:47:6d:5c:e0:d6:cd plex@minibian
The key's randomart image is:
+---[RSA 2048]----+
|                 |
|   o o           |
|o + + o o        |
|.B   + o E       |
|o o + o S        |
|.  . + .         |
| o. .            |
|+...             |
|*+.              |
+-----------------+
plex@minibian:~$ cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
plex@minibian:~$ ssh plex@192.168.1.129
Password:
Password:
Password:
`

**Comment by pisteps** [comment]
`plex@minibian:~$ ssh-keygen

Generating public/private rsa key pair.

Enter file in which to save the key (/home/plex/.ssh/id_rsa): 

/home/plex/.ssh/id_rsa already exists.

Overwrite (y/n)? y

Enter passphrase (empty for no passphrase): 

Enter same passphrase again: 

Your identification has been saved in /home/plex/.ssh/id_rsa.

Your public key has been saved in /home/plex/.ssh/id_rsa.pub.

The key fingerprint is:

02:89:4e:e9:b0:a1:ae:cb:a1:e9:47:6d:5c:e0:d6:cd plex@minibian

The key's randomart image is:

+---[RSA 2048]----+
|                 |
|   o o           |
|o + + o o        |
|.B   + o E       |
|o o + o S        |
|.  . + .         |

| o. .            |

|+...             |

|*+.              | 

+-----------------+

plex@minibian:~$ cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

plex@minibian:~$ ssh plex@192.168.1.129


Password:
Password:
Password:
`

**Comment by pisteps** [comment]
thank you.
i don't get this part.
that's what i did on the master

`plex@minibian:~$ ssh-keygen

Generating public/private rsa key pair.

Enter file in which to save the key (/home/plex/.ssh/id_rsa): 

/home/plex/.ssh/id_rsa already exists.

Overwrite (y/n)? y

Enter passphrase (empty for no passphrase): 

Enter same passphrase again: 

Your identification has been saved in /home/plex/.ssh/id_rsa.

Your public key has been saved in /home/plex/.ssh/id_rsa.pub.

The key fingerprint is:

0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx plex@minibian

The key's randomart image is:

+---[RSA 2048]----+

|                 |

|   o o           |

|o + + o o        |
|.B   + o E       |
|o o + o S        |
|.  . + .         |
| o. .            |
|+...             |
|*+.              |
+-----------------+

plex@minibian:~$ cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

plex@minibian:~$ ssh plex@192.168.1.129

Password:

Password:

Password:
`

**Comment by pisteps** [comment]
maybe i am close to a solution.
the ubuntu server (slave) has not a ssh-server installed by default. 
later i try to install it... that should solve the problem (i hope)

**Comment by pisteps** [comment]
i finally managed to ssh with key from plex (master) to plex (slave). 
since the slave is a virtual machine, i had to forward port 22 (of ubuntu virtualbox) to port XX of the guest-machine. 
to ssh from plex (master) i have to specify the port:
`ssh -p XX plex@slaveIP`

i assume (correct me if i am wrong) that when i run this command from the master:
`sudo -u plex -H prt add_host` 
i have to use XX instead of 22.

having done that, when i try to play a movie from plex web  i get a message: " impossible to play this item".
looks like there is a problem with the /opt/plex/tmp folder and the samba share. 
when i first try to play a video on plex web, in the slave screen i get this message:
CIFS VFS: Autodisabling the use of server inode numbers on \masterIPaddres\opt\plex\tmp. this server doesn't seem to support them properly. hardlinks will not be recognized on this mount.

**Comment by pisteps** [comment]
reverted to use default transcode directory (which is already shared with the slave because is in /var/lib/plexmediaserver/...)

though same problem, can't play video

**Comment by pisteps** [comment]
the plex user (slave) couldn't write on the shared directory.
that problem is fixed now.

when i try to play a video, now i can see quite an increase in the CPU used by the ubuntu server -virtualbox. that makes me thing that is actually starting to transcode maybe.
though the video keep loading and after a while on the slave interface i get the following message:
out of memory: kill process 1390 (plex_transcoder) score 3 or sacrifice child
killed process 1394 (plex_transcoder) total-vm:60444kB, anon-rss:0kB, file-rss:4kB

can it be that the virtual machine is not properly set in terms of memory/cpu allocated?
any suggestion on how to set those parameters?

**Comment by wnielson** [comment]
I'm going to close this as the issue doesn't seem to be related to `PRT`.  Feel free to follow up though if you think the information might be useful to others!
