### ISSUE TITLE
Will not work with "media optimization"

### ISSUE THREAD

**Issue by kylinblue** [wnielson/Plex-Remote-Transcoder#31]
The streaming/transcoding is working fine on my setup. All attempt to optimize a video return fail immediately.

**Comment by wnielson** [comment]
Good news, this is an easy fix.  You need to edit your NFS mount for your media directory on the `master` to be read-write (in the setup guide we have is exported as read-only).  In my setup this involved opening `/etc/exports` and changing

```
/mnt/media               10.99.0.12(ro,sync,no_subtree_check)
```

to (notice the `rw`)

```
/mnt/media               10.99.0.12(rw,sync,no_subtree_check)
```

Restart `NFS` on the `master`

```
sudo /etc/init.d/nfs-kernel-server restart
```

Finally, one each of your transcode machines, you'll need to remount the media directories.  In my case:

```
sudo umount /mnt/media
sudo mount /mnt/media
```

**Comment by wnielson** [comment]
I've updated the wiki to address the configuration needed to get this to work.
