### ISSUE TITLE
Project Architecture: Abstraction of custom transcoder

### ISSUE THREAD

**Issue by deevus** [wnielson/Plex-Remote-Transcoder#35]
Hi guys

I think this is a really cool project, but I'm wondering if your approach might be making this harder than it needs to be. 

Correct me if I'm wrong, but from what I've read of the source code and gathered from the Ubuntu tutorial, the crux of the project is supporting a drop-in replacement of the default Plex transcoder binary. 

I'm wondering if it might be better to solve that problem in a general sense first, rather than the strongly coupled solution that this seems to be currently. That is, partition this project so that it's solving one problem at a time, rather than all at once. 

I think that by solving the problem of a drop-in replacement transcoder first, it will make the rest much simpler, and it's likely that there may be other applications that could benefit from replacing the binary.

That being said... this isn't my project so I'm not trying to tell you what to do, but being OSS you're probably hoping for as much help as you can get.

**Comment by wnielson** [comment]
Hey @deevus, thanks for joining the discussion!  To try to keep things 'simple', this project tries to leverage as many other tools as it can (nfs, ssh, etc.).  This makes configuration and setup more complicated but it keeps the code relatively straightforward.

Do you have specifics in mind for making things less complicated?

**Comment by deevus** [comment]
No problem

I was specifically referring to replacing the default transcoder binary. I think if there was a project specifically for solving that problem: managing an interface between

a) a plex server
b) a custom transcoder implementation

then this project doesn't have to worry about interop between the plex server and the transcoder (in the case where the interface changes), because that would be the job of the parent project. 

Does that make sense?

**Comment by wnielson** [comment]
I see what you're saying.  I'd be curious if you have or have heard of project ideas that would benefit from having a "man in the middle" Plex transcoder.  It is an interesting idea, but if I have to maintain two projects instead of one that kind of makes things more difficult, not less.  That said, if there was enough interest in a replacement Plex transcoder that basically provided an API, maybe it would be worth the effort.
