### ISSUE TITLE
REMOTE_ARGS doesn't work with spaces in the {working_dir}

### ISSUE THREAD

**Issue by rob256** [wnielson/Plex-Remote-Transcoder#36]
This is for a Synology NAS as the master.

When it tries to ssh to the slave, it attempts `cd` to a temp directory for transcoding:
`cd /volume1/plex-share/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions/plex-transcode-EF1D45F5-04E2-43C6-86B5-6876B81C08E3-35197b68-0b9b-41da-b9a0-a5a0da4c5dfd`

Unfortunately, due to spaces in some of the folder names, the command fails, and temp files are dumped on the slave in the `$HOME` directory instead.

This only seemed to affect transcoding on the mobile.

**Comment by wnielson** [comment]
Thanks for the report.  This should be an easy fix.

**Comment by wnielson** [comment]
Just pushed a fix.  Please test.

**Comment by rob256** [comment]
Yep, that seems to do the trick! Thanks!

**Comment by wnielson** [comment]
Great!
