### ISSUE TITLE
Local + remote transcode at same time ?

### ISSUE THREAD

**Issue by ghost** [wnielson/Plex-Remote-Transcoder#38]
I was wondering if I understood correctly how this works :yum: 

So If I have 1 big server which do a pretty good work in transcoding
but after some time I have too many users for the server and decide to buy another server
just to support the transcoding. 

Will the main server transcode too ? Or just the new server I'll have bought would transcode ?

**Comment by rob256** [comment]
You can add 127.0.0.1 to the list of hosts. That way it will distribute the load to both the remote and local servers.

**Comment by wnielson** [comment]
You would be able to use both servers simultaneously.

**Comment by ghost** [comment]
Oh thank you ! I thought it would only use the second one haha ^^
