### ISSUE TITLE
The UID is already in use

### ISSUE THREAD

**Issue by PaiSolutions** [wnielson/Plex-Remote-Transcoder#39]
sudo adduser --uid 111 --gid 117 plex --home /var/lib/plexmediaserver --no-create-home
adduser: The UID 111 is already in use.

how can i fix this up, Im building my third machine and the other two are fine.

**Comment by PaiSolutions** [comment]
FIXED!

**Comment by wnielson** [comment]
How did you fix it?  Is it something worth sharing for future users?
