### ISSUE TITLE
Issue with latest plex version

### ISSUE THREAD

**Issue by nogardvfx** [wnielson/Plex-Remote-Transcoder#40]
Hello, first off, great program.  Been using it since the beginning.  Never had an issue with it, until now.
I upgraded to version 1.1.3.2700-6f64a8d under Ubuntu 14.  I had to upgrade to the latest version of PRT as well.  Setup runs great, no errors.  But when it comes to playing any transcoded video, it just sits for about 10-15 seconds and then quits.  I am running htop --user=plex on the master to see if I notice anything, and I see a blip of something on the video I am playing and then nothing.  I never see anything on the slave.  Really love the app, but I am at a loss as to what to do now as I have never had any issues.

What information can I get that would help get this working again?

Cheers,
-Chris

**Comment by liviynz** [comment]
I had an issue with the latest one but was just with one particular mkv which I just switched the container to MP4, no re-encoding and it started working. I suspect it's a bug with 1.3 PMS itself.

**Comment by nogardvfx** [comment]
I tried several files, ones which I know worked fine in the past.  Also, I automatically encode everything to MP4.

**Comment by Allram** [comment]
did you delete the plex-codec directory when installed PRT again? (/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Codecs/5a2d9a2-1127-linux-ubuntu-x86_64 ) & /usr/lib/plexmediaserver/plex_transcoder) I needed to delete that before installing PRT after Plex update to make it work again.

**Comment by wnielson** [comment]
If @Allram suggestion doesn't work, feel free to reopen this.   `PRT` is known to work with the latest versions of `PMS`.
