### ISSUE TITLE
Can we upgrade to 1.1?

### ISSUE THREAD

**Issue by chimpy** [wnielson/Plex-Remote-Transcoder#44]
Hi guys,

Wondering whether we can upgrade to the latest version of PMS yet or not. Kudos for the great project :)

Thanks!

**Comment by wnielson** [comment]
`1.1.3.2700-6f64a8d` is confirmed working.  I should have time this weekend to get the newest version (`1.1.4.2757-24ffd60`) working.

**Comment by Drewster727** [comment]
@wnielson just wanted to echo the kudos from @chimpy -- this project is fantastic :+1:

**Comment by chimpy** [comment]
I only ask because I tried it and whilst I see the file transcoding on the slave, the client's loading icon just keeps spinning.

I'm not sure whether I've configured something incorrectly or not.

To clarify: after a Plex upgrade, the _only_ thing to do is prt overwrite? Nothing else?

Thanks!

**Comment by wnielson** [comment]
Thanks @Drewster727 

@chimpy Yes, usually `prt overwrite` does the job.  Something was probably changed under the hood by the Plex team.  We'll know more once I dive in.  I'll keep you posted.

**Comment by wnielson** [comment]
I just installed version `1.1.4.2757-24ffd60` and it is working fine.

**Comment by pironic** [comment]
just tested with plexpass version `1.2.2.2857-d34b464` and it works... i just need to upgrade my slave :/
