### ISSUE TITLE
Sync Issue 

### ISSUE THREAD

**Issue by dhruvb14** [wnielson/Plex-Remote-Transcoder#46]
Hey @wnielson thanks for all your hard work, got everything setup this weekend and have 2 slaves working flawlessly for transcoding real time playback. However when I sync a bunch of shows to my iPad i keep getting a transcoder error on the iPad. I did some digging around and found that I if I update my exports to rw instead of ro then I can get this problem resolved. It does partially resolve the problem but here is the issue.

How I reproduce:

1. On my iPad I set 2 shows to sync
2. First show starts converting and copying over fine
3. Second show begins converting and fails with a transcoder error.
4. Try adding same show by itself and it'll sync
5. While the show from step 4 is syncing add another show
6. once the show from 4 is done it spawns up another thread for the next show and fails again.

I would love some assistance as I have been trying to read the logs to make sense of it but am lost

**Comment by wnielson** [comment]
Thanks for the feedback.  I haven't done much testing with sync, so I'm not surprised it doesn't work very well.  Anyway, I'll try to find some time to take a look at this.  If you're feeling adventurous, taking a look at the Plex Media Server logs should help track down the issue.

**Comment by dhruvb14** [comment]
I forgot to mention I got this resolved. One of my nodes was marked RO for the plex library folder so when it chose that server it failed instantly. I currently have optimized versions, sync and live transcoding working flawlessly and can now transcode 7-10 720p steams simultaneously. Next project is setting this up in the cloud since I have gigabit upload and leaving my main node at home and all my transcode slaves in cloud.
