### ISSUE TITLE
Jan 22 08:51:45 plex sh[824]: ssh: /usr/lib/plexmediaserver/libcrypto.so.1.0.0: no version information available (required by ssh)

### ISSUE THREAD

**Issue by milligan** [wnielson/Plex-Remote-Transcoder#50]
Hello,

I found this project after suffering problems with my virtual plex machine not being powerful enough to transcode movies. I have a couple processing beasts that I would like to load balance with. Throughout my setup, I run debian 8.6.

I have set up everything according to the debian wiki. My plex version is: Version 1.0.3.2461

Everything mounts and seems to be working, but as soon as I try to watch a movie I get the following error before plex reports it was unable to play the media.

Jan 22 08:51:45 plex sh[824]: ssh: /usr/lib/plexmediaserver/libcrypto.so.1.0.0: no version information available (required by ssh)
Jan 22 08:51:45 plex sh[824]: ssh: /usr/lib/plexmediaserver/libcrypto.so.1.0.0: no version information available (required by ssh)
Jan 22 08:51:45 plex sh[824]: ssh: /usr/lib/plexmediaserver/libcrypto.so.1.0.0: no version information available (required by ssh)
Jan 22 08:51:45 plex sh[824]: ssh: /usr/lib/plexmediaserver/libcrypto.so.1.0.0: no version information available (required by ssh)
Jan 22 08:51:46 plex sh[824]: Traceback (most recent call last):
Jan 22 08:51:46 plex sh[824]: File "/usr/local/bin/prt_local", line 9, in <module>
Jan 22 08:51:46 plex sh[824]: load_entry_point('prt==0.4.2', 'console_scripts', 'prt_local')()
Jan 22 08:51:46 plex sh[824]: File "build/bdist.linux-x86_64/egg/prt.py", line 297, in transcode_local
Jan 22 08:51:46 plex sh[824]: File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
Jan 22 08:51:46 plex sh[824]: errread, errwrite)
Jan 22 08:51:46 plex sh[824]: File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
Jan 22 08:51:46 plex sh[824]: raise child_exception
Jan 22 08:51:46 plex sh[824]: OSError: [Errno 2] No such file or directory

I have verified that all mentioned files in the error messages here actually exist on both master and slave.

Hope there is a fix for this - it would really benefit me!

Thanks,
Kristoffer

**Comment by wnielson** [comment]
It appears that it is [this line](https://github.com/wnielson/Plex-Remote-Transcoder/blob/master/prt.py#L297) that is failing, which would imply that either [`get_transcoder_path`](get_transcoder_path) is returning the wrong path to the transcoder or that the transcoder is not installed.  On Linux, this path should be `/usr/lib/plexmediaserver/plex_transcoder`.

**Comment by ChoosenEye** [comment]
Ok i see you used the Wiki Article from me ^^

Please dont use the latest release just git clone the actual master because there the path is fixed.

@wnielson please push a new release from the actual master... so its working on all linux versions. Thanks

**Comment by ChoosenEye** [comment]
@wnielson ty for the push.

@milligan just use the 0.4.2 release from now it should be working flawless.

**Comment by wnielson** [comment]
@ChoosenEye Released version 0.4.2

**Comment by milligan** [comment]
Thank you both, that seems to have corrected the problem and it's now working. I'm amazed at how CPU intensive the converter is though.

Has it been benchmarked to give an indication on how hard it will hit my processing machines? i.e if I set up a slave on my gaming computer - will I notice transcoding while playing my games?

**Comment by ChoosenEye** [comment]
no problem.

Yes its CPU intensive but you are transcoding videos ^^ The Plex Remote transcoder doesn't minimize CPU Usage its just load balance between your transcoding hosts.

For notice 2k Passmark Score you will need for around 1x 1080p 6-8mbps stream.

@milligan if all is working now please close the issue.
