### ISSUE TITLE
Plex upgrade/prt install incompatibility 

### ISSUE THREAD

**Issue by liviynz** [wnielson/Plex-Remote-Transcoder#6]
There's a problem after you install plex, install prt and then upgrade plex...if you try and do a install prt again it fails because it's already done a rename previously however the script version of "Plex New Transcoder" has been overwritten by the upgrade.

Today I've been learning python and coded a new function for prt to allow for this situation with a specific switch/argument called "overwrite". That will check prt is already installed, binary has been renamed but the original has been overwritten by an upgrade and then will redo the rename & install in it's place but without setting up the config (as already there).

I'll be doing some testing over the next few days of this to ensure my limit python coding is all ok. After that I'm happy to share it with you if that's ok? I also have some other fixes/additional functionality that I'd like to help you with.

Cheers

**Comment by grokdesigns** [comment]
@liviynz Can you provide your fix for this?

**Comment by liviynz** [comment]
Hey,

I'll put it through a bit more testing and then I will. I've coded in other languages before but not Python so just need to make sure it's right in a separate test env which I just built today. 

I've got some other upgrades in mind after this including selective slaves for particular tasks (e.g. Thumbnail generation/gracenote fingerprinting/general transcoding), better load leveling to give slaves performance values, etc. Also an easy guide on trimming down the OS to remove excess overhead that you don't require for slaves (removing desktop, extra services, etc).

Code coming shortly, how do you want me to pass it to yourself?

Cheers

**Comment by JigSawFr** [comment]
With a Pull Request, a Fork on your github Account or à Gist. Thank you for your work !

**Comment by grokdesigns** [comment]
@liviynz That all sounds great! Thank you for your work on this! As @JigSawFr said, if you could fork it on your account or create a Gist, that would be awesome!

**Comment by wnielson** [comment]
I'd welcome a pull request!

**Comment by liviynz** [comment]
Pull request there, I've tested it and it seems ok. I fixed this issue and also did a few other small things plus some todo's in there.

**Comment by liviynz** [comment]
FYI, using my current 0.2.1 branch (with the get_load bug fix) I successfully used the overwrite function after upgrading to the latest PMS version (rather than simulating an upgrade as I did during my testing). I also happily got an error when trying to use the overwrite function & the binary was in use (which it was by 2 streams) and after stopping PMS the overwrite completed successfully and everything was double rainbows from there on :)

**Comment by liviynz** [comment]
Fixed in 0.2.1
