### ISSUE TITLE
running prt check_config: KeyError: 'TranscoderTempDirectory' 

### ISSUE THREAD

**Issue by stratus-ss** [wnielson/Plex-Remote-Transcoder#69]
I am testing PRT and I was just looking to see what things did. When I try to run `prt check_config` I get the following error

```plex@prt:~$ prt check_config
Performing PRT configuration check

Plex Username: 
Plex Password: 
Traceback (most recent call last):
  File "/usr/local/bin/prt", line 9, in <module>
    load_entry_point('prt==0.4.4', 'console_scripts', 'prt')()
  File "build/bdist.linux-x86_64/egg/prt.py", line 722, in main
  File "build/bdist.linux-x86_64/egg/prt.py", line 552, in check_config
KeyError: 'TranscoderTempDirectory'
```
The problem line(s):

```
    paths_modes = {
        5: media_paths,
        7: [settings['TranscoderTempDirectory']]
    }
```

I assume that something is missing out of the ~/.prt.conf but I am not sure where it gets this information. I went over the ubuntu wiki at least 3 times but I can't figure out what I am doing wrong. Any help is appreciated

**Comment by nagadevkrishna** [comment]
Look at your Plex Server Settings > Transcoder >Transcoder temporary directory. ex: /opt/plex/tmp

**Comment by liviynz** [comment]
Correct, that’s where prt gets its value...have a look at the readme, it does mention it in a few places
