### ISSUE TITLE
Fatal error when doing Ubuntu install

### ISSUE THREAD

**Issue by IvanCharcos** [wnielson/Plex-Remote-Transcoder#72]
Hello,

I am getting the error below when doing the Ubuntu Install tutorial.
I am not really sure what it means.

Is it possible for you to take a look?

`Installed /usr/local/lib/python2.7/dist-packages/prt-0.4.4-py2.7.egg
Processing dependencies for prt==0.4.4
Searching for psutil
Reading https://pypi.python.org/simple/psutil/
Best match: psutil 5.4.3
Downloading https://pypi.python.org/packages/e2/e1/600326635f97fee89bf8426fef14c5c29f4849c79f68fd79f433d8c1bd96/psutil-5.4.3.tar.gz#md5=3b291833dbea631db9d271aa602a169a
Processing psutil-5.4.3.tar.gz
Writing /tmp/easy_install-1l9mJ7/psutil-5.4.3/setup.cfg
Running psutil-5.4.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1l9mJ7/psutil-5.4.3/egg-dist-tmp-3FWNJF
psutil/_psutil_common.c:9:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

Thanks,
Ivan

**Comment by liviynz** [comment]
Try installing the psutil package and then trying again.

To install it use the commands

`sudo apt-get update && sudo apt-get install python-psutil`

And that should fix it.

**Comment by IvanCharcos** [comment]
Thank you, that did it!
