### ISSUE TITLE
Command to view current status

### ISSUE THREAD

**Issue by wnielson** [wnielson/Plex-Remote-Transcoder#9]
It would be nice to have a command for viewing the current status and state of transcode jobs across all nodes.

**Comment by liviynz** [comment]
Yeah, this is a good feature to have...I've been having all the logs going to one area (/opt/plex/tmp/prt/log) so any of the prt scripts on any system can update it. Not quite the same but gives a single place to be able to pull the info.

**Comment by wnielson** [comment]
Initial implementation has been added in 60854f021f411fe635dacc3b2d34d23f5f9dcb0d.
